---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: httpbin
  name: httpbin
  namespace: diag
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: httpbin
    deployment: httpbin
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: httpbin
  name: httpbin-lb
  namespace: diag
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: httpbin
    deployment: httpbin
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpbin
  name: httpbin
  namespace: diag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      deployment: httpbin
  template:
    metadata:
      labels:
        app: httpbin
        deployment: httpbin
    spec:
      containers:
      - image: ghcr.io/mccutchen/go-httpbin:latest
        name: minion
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: httpbin
  name: httpbin
  namespace: diag
spec:
  port:
    targetPort: 8080-tcp
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: httpbin
    weight: 100
  wildcardPolicy: None
