---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-receiver
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: debug-receiver
  template:
    metadata:
      labels:
        app: debug-receiver
    spec:
      containers:
      - image: registry.access.redhat.com/ubi8/python-311:latest
        name: debug
        command:
          - /bin/sh
          - -c
          - |
            pip -q --no-cache install -U pip
            pip -q --no-cache install pyserv
            serv 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: debug-receiver
  name: debug-receiver
spec:
  ports:
  - name: alert-debug-receiver
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: debug-receiver
  sessionAffinity: None
  type: ClusterIP