kind: Secret
apiVersion: v1
metadata:
  name: alertmanager-main
  namespace: openshift-monitoring
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      http_config:
        proxy_from_environment: true
    inhibit_rules:
      - equal:
          - namespace
          - alertname
        source_matchers:
          - severity = critical
        target_matchers:
          - severity =~ warning|info
      - equal:
          - namespace
          - alertname
        source_matchers:
          - severity = warning
        target_matchers:
          - severity = info
    receivers:
      - name: Critical
        webhook_configs:
          - url: 'http://debug-receiver.diag.svc.cluster.local:8080/alert'
      - name: Default
        webhook_configs:
          - url: 'http://debug-receiver.diag.svc.cluster.local:8080/alert'
      - name: Watchdog
        webhook_configs:
          - url: 'http://debug-receiver.diag.svc.cluster.local:8080/alert'
    route:
      group_by:
        - namespace
      group_interval: 5m
      group_wait: 30s
      receiver: Default
      repeat_interval: 12h
      routes:
        - receiver: Watchdog
          matchers:
            - alertname = Watchdog
        - receiver: Critical
          matchers:
            - severity = critical
