apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-pipelines-console-plugin
  namespace: openshift-operators
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: job-pipelines-console-plugin
rules:
- apiGroups:
  - operator.openshift.io
  resources:
  - consoles
  verbs:
  - get
  - list
  - patch
  - label
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: job-pipelines-console-plugin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: job-pipelines-console-plugin
subjects:
- kind: ServiceAccount
  name: job-pipelines-console-plugin
  namespace: openshift-operators
---
apiVersion: v1
data:
  console-plugin-job.sh: |
    #!/usr/bin/bash

    enable_console_plugin(){
      [ -z "${PLUGIN_NAME}" ] && return 1

      echo "Attempting to enable ${PLUGIN_NAME} plugin"
      echo ""

      # Create the plugins section on the object if it doesn't exist
      if [ -z "$(oc get consoles.operator.openshift.io cluster -o=jsonpath='{.spec.plugins}')" ]; then
        echo "Creating plugins object"
        oc patch consoles.operator.openshift.io cluster --patch '{ "spec": { "plugins": [] } }' --type=merge
      fi

      INSTALLED_PLUGINS=$(oc get consoles.operator.openshift.io cluster -o=jsonpath='{.spec.plugins}')
      echo "Current plugins:"
      echo "${INSTALLED_PLUGINS}"

      if [[ "${INSTALLED_PLUGINS}" == *"${PLUGIN_NAME}"* ]]; then
          echo "${PLUGIN_NAME} is already enabled"
      else
          echo "Enabling plugin: ${PLUGIN_NAME}"
          oc patch consoles.operator.openshift.io cluster --type=json --patch '[{"op": "add", "path": "/spec/plugins/-", "value": "'"${PLUGIN_NAME}"'"}]'
      fi

      sleep 6
      oc get consoles.operator.openshift.io cluster -o=jsonpath='{.spec.plugins}'
    }

    enable_console_plugin
kind: ConfigMap
metadata:
  name: job-pipelines-console-plugin
  namespace: openshift-operators
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: job-pipelines-console-plugin
  namespace: openshift-operators
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - /scripts/console-plugin-job.sh
        env:
        - name: PLUGIN_NAME
          value: pipelines-console-plugin
        image: registry.redhat.io/openshift4/ose-cli
        name: minion
        volumeMounts:
        - mountPath: /scripts
          name: scripts
      restartPolicy: Never
      serviceAccount: job-pipelines-console-plugin
      serviceAccountName: job-pipelines-console-plugin
      volumes:
      - configMap:
          defaultMode: 493
          name: job-pipelines-console-plugin
        name: scripts
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-pipelines-operator-rh
  namespace: openshift-operators
spec:
  channel: latest
  installPlanApproval: Automatic
  name: openshift-pipelines-operator-rh
  source: redhat-operators
  sourceNamespace: openshift-marketplace
